"""Attribution and idempotency contracts for recommendation telemetry."""

from app.models import (
    Track,
    rec_impressions,
    recommendation_events,
    recommendation_impressions,
)
from app.recommendation_scoring import ALGORITHM_VERSION
from app.recommendation_telemetry import record_delivery
from app.schemas import TrackResponse
from tests.conftest import auth_headers, create_user


def _local_track(db, title="candidate"):
    track = Track(
        title=title,
        artist="Telemetry Artist",
        duration=180,
        source="local",
        file_path=f"minio://music/{title}.mp3",
        play_count=7,
    )
    db.add(track)
    db.commit()
    db.refresh(track)
    return track


def _patch_cached_recs(db, monkeypatch, cached_score=1.2345):
    from app.routers import recommendations as recommendations_router

    track = _local_track(db, "cached-candidate")
    cached_track = TrackResponse.model_validate(track).model_copy(
        update={
            "recommendation_id": "cache-fill-id",
            "recommendation_surface": "library",
            "recommendation_position": 0,
            "recommendation_score": cached_score,
            # Simulate a cache entry generated by a previous scorer rollout.
            "recommendation_model_version": "legacy-v3",
        }
    )
    cached = {
        "tracks": [cached_track.model_dump(mode="json")],
        "playlists": [],
    }
    monkeypatch.setattr(recommendations_router, "get_cache", lambda _key: cached)


def _delivery_rows(db, user_id):
    return db.execute(
        recommendation_impressions.select()
        .where(recommendation_impressions.c.user_id == user_id)
        .order_by(recommendation_impressions.c.id)
    ).mappings().all()


def test_repeated_cached_response_is_one_delivery(client, db, monkeypatch):
    """Повтор того же кэша в окне дедупликации — одна выдача: тот же
    request_id и один набор строк показа, а не по набору на каждый GET."""
    user = create_user(db, username="dedup-recs-user")
    cached_score = 1.2345
    _patch_cached_recs(db, monkeypatch, cached_score)

    headers = auth_headers(client, username=user.username)
    first = client.get("/api/recommendations/", headers=headers)
    second = client.get("/api/recommendations/", headers=headers)

    assert first.status_code == 200, first.text
    assert second.status_code == 200, second.text
    first_track = first.json()["tracks"][0]
    second_track = second.json()["tracks"][0]
    assert first_track["recommendation_id"] != "cache-fill-id"
    assert first_track["recommendation_id"] == second_track["recommendation_id"]
    assert second_track["recommendation_position"] == 0
    assert second_track["recommendation_model_version"] == ALGORITHM_VERSION

    rows = _delivery_rows(db, user.id)
    assert len(rows) == 1
    assert rows[0]["request_id"] == first_track["recommendation_id"]
    assert rows[0]["score"] == cached_score
    assert rows[0]["visible"] is False
    assert rows[0]["algorithm_version"] == ALGORITHM_VERSION


def test_invalidation_starts_a_new_delivery(client, db, monkeypatch):
    """После сброса кэша (лайк, прослушивание…) — новая выдача с новым id."""
    from app.recommendation_cache import invalidate_recommendation_cache

    user = create_user(db, username="dedup-reset-user")
    _patch_cached_recs(db, monkeypatch)

    headers = auth_headers(client, username=user.username)
    first = client.get("/api/recommendations/", headers=headers)
    invalidate_recommendation_cache(user.id)
    second = client.get("/api/recommendations/", headers=headers)

    first_id = first.json()["tracks"][0]["recommendation_id"]
    second_id = second.json()["tracks"][0]["recommendation_id"]
    assert first_id != second_id
    assert [row["request_id"] for row in _delivery_rows(db, user.id)] == [
        first_id,
        second_id,
    ]


def test_cache_hit_reuses_fresh_computation_delivery(client, db):
    """Отдача из кэша сразу после расчёта — та же выдача, что и расчёт."""
    user = create_user(db, username="dedup-miss-user")
    _local_track(db, "fresh-candidate")

    headers = auth_headers(client, username=user.username)
    first = client.get("/api/recommendations/", headers=headers)
    second = client.get("/api/recommendations/", headers=headers)
    assert first.status_code == 200, first.text
    assert second.status_code == 200, second.text

    assert first.json()["tracks"], "пустая выдача — тесту нечего проверять"
    first_ids = {t["recommendation_id"] for t in first.json()["tracks"]}
    second_ids = {t["recommendation_id"] for t in second.json()["tracks"]}
    assert first_ids == second_ids
    rows = _delivery_rows(db, user.id)
    assert {row["request_id"] for row in rows} <= first_ids
    assert len(rows) == len(first.json()["tracks"])


def test_cached_response_gets_a_fresh_delivery_id(client, db, monkeypatch):
    """A cached ranking is reusable; its delivery/request id is not — once the
    dedup window is over."""
    from app.cache import clear_pattern
    from app.routers import recommendations as recommendations_router

    user = create_user(db, username="cached-recs-user")
    track = _local_track(db, "cached-candidate")
    cached_score = 1.2345
    cached_track = TrackResponse.model_validate(track).model_copy(
        update={
            "recommendation_id": "cache-fill-id",
            "recommendation_surface": "library",
            "recommendation_position": 0,
            "recommendation_score": cached_score,
            # Simulate a cache entry generated by a previous scorer rollout.
            "recommendation_model_version": "legacy-v3",
        }
    )
    cached = {
        "tracks": [cached_track.model_dump(mode="json")],
        "playlists": [],
    }
    monkeypatch.setattr(recommendations_router, "get_cache", lambda _key: cached)

    headers = auth_headers(client, username=user.username)
    first = client.get("/api/recommendations/", headers=headers)
    # Окно дедупликации истекло (ключ с TTL — эмулируем удалением).
    clear_pattern("recs:*:delivery")
    second = client.get("/api/recommendations/", headers=headers)

    assert first.status_code == 200, first.text
    assert second.status_code == 200, second.text
    first_track = first.json()["tracks"][0]
    second_track = second.json()["tracks"][0]
    assert first_track["recommendation_id"] != second_track["recommendation_id"]
    assert first_track["recommendation_position"] == 0
    assert second_track["recommendation_position"] == 0
    assert first_track["recommendation_model_version"] == ALGORITHM_VERSION
    assert second_track["recommendation_model_version"] == ALGORITHM_VERSION

    rows = db.execute(
        recommendation_impressions.select()
        .where(recommendation_impressions.c.user_id == user.id)
        .order_by(recommendation_impressions.c.id)
    ).mappings().all()
    assert len(rows) == 2
    assert [row["request_id"] for row in rows] == [
        first_track["recommendation_id"],
        second_track["recommendation_id"],
    ]
    assert all(row["score"] == cached_score for row in rows)
    assert all(row["visible"] is False for row in rows)
    assert all(row["algorithm_version"] == ALGORITHM_VERSION for row in rows)


def test_external_impression_after_materialization_is_idempotent(client, db):
    """A new local id must still match the provider-backed delivery row."""
    user = create_user(db, username="external-impression-user")
    request_id = "external-delivery"
    external_id = "video-123"
    record_delivery(
        db,
        user_id=user.id,
        items=[
            {
                "id": f"ytmusic:{external_id}",
                "source": "ytmusic",
                "external_id": external_id,
                "title": "External candidate",
                "artist": "Provider Artist",
            }
        ],
        surface="flow",
        request_id=request_id,
    )
    db.commit()

    materialized = Track(
        title="External candidate",
        artist="Provider Artist",
        duration=180,
        source="ytmusic",
        external_id=external_id,
    )
    db.add(materialized)
    db.commit()
    db.refresh(materialized)

    payload = {
        "event_type": "impression",
        "track_id": materialized.id,
        "source": "ytmusic",
        "external_id": external_id,
        "surface": "flow",
        "position": 0,
        "request_id": request_id,
        # The client cannot rewrite the server-side attribution label.
        "algorithm_version": "client-forged-v0",
    }
    headers = auth_headers(client, username=user.username)
    first = client.post("/api/recommendations/events", json=payload, headers=headers)
    second = client.post("/api/recommendations/events", json=payload, headers=headers)
    assert first.status_code == 204, first.text
    assert second.status_code == 204, second.text

    delivery = db.execute(
        recommendation_impressions.select().where(
            recommendation_impressions.c.request_id == request_id
        )
    ).mappings().one()
    assert delivery["visible"] is True
    assert delivery["track_id"] == materialized.id

    fatigue = db.execute(
        rec_impressions.select().where(
            rec_impressions.c.user_id == user.id,
            rec_impressions.c.track_id == materialized.id,
        )
    ).mappings().one()
    assert fatigue["shown_count"] == 1

    events = db.execute(
        recommendation_events.select().where(
            recommendation_events.c.user_id == user.id,
            recommendation_events.c.request_id == request_id,
            recommendation_events.c.event_type == "impression",
        )
    ).mappings().all()
    assert len(events) == 1
    assert events[0]["track_id"] == materialized.id
    assert events[0]["algorithm_version"] == ALGORITHM_VERSION


def test_external_impression_before_materialization_is_linked_on_import(client, db):
    user = create_user(db, username="external-before-import-user")
    request_id = "external-before-import"
    external_id = "video-before-import"
    record_delivery(
        db,
        user_id=user.id,
        items=[
            {
                "id": f"ytmusic:{external_id}",
                "source": "ytmusic",
                "external_id": external_id,
                "title": "Pending external candidate",
                "artist": "Pending Artist",
            }
        ],
        surface="flow",
        request_id=request_id,
    )
    db.commit()

    headers = auth_headers(client, username=user.username)
    impression = client.post(
        "/api/recommendations/events",
        headers=headers,
        json={
            "event_type": "impression",
            "source": "ytmusic",
            "external_id": external_id,
            "surface": "flow",
            "position": 0,
            "request_id": request_id,
            "algorithm_version": ALGORITHM_VERSION,
        },
    )
    assert impression.status_code == 204, impression.text

    imported = client.post(
        "/api/tracks/import",
        headers=headers,
        json={
            "source": "ytmusic",
            "external_id": external_id,
            "title": "Pending external candidate",
            "artist": "Pending Artist",
            "duration": 180,
        },
    )
    assert imported.status_code == 200, imported.text
    track_id = imported.json()["id"]

    delivery = db.execute(
        recommendation_impressions.select().where(
            recommendation_impressions.c.request_id == request_id
        )
    ).mappings().one()
    assert delivery["visible"] is True
    assert delivery["track_id"] == track_id

    fatigue = db.execute(
        rec_impressions.select().where(
            rec_impressions.c.user_id == user.id,
            rec_impressions.c.track_id == track_id,
        )
    ).mappings().one()
    assert fatigue["shown_count"] == 1
